const express = require('express');
const router = express.Router();
const wrapAsync = require("../utils/wrapAsync.js");
const {isLoggedIn,isOwner,validatelisting} = require("../middleware.js");
const listingController = require("../controllers/listings.js");
const multer  = require('multer');
const {storage} = require("../cloudconfig.js");
const Listing = require('../models/listing.js');
const upload = multer({storage });
router.route("/").get(wrapAsync(listingController.index)).post(isLoggedIn,upload.single('listing[image]'),validatelisting,wrapAsync(listingController.createListing));
router.get("/new",isLoggedIn,listingController.renderNewForm);
router.get("/trending",wrapAsync(listingController.trending));
router.get("/rooms", wrapAsync(listingController.rooms));
router.get("/camping",wrapAsync(listingController.camping));
router.get("/castles", wrapAsync(listingController.castles));
router.get("/farms", wrapAsync(listingController.farms));
router.get("/arctic", wrapAsync(listingController.arctic));
router.get("/amazingpools", wrapAsync(listingController.amazingpools));
router.get("/mountains", wrapAsync(listingController.mountains));
router.get("/iconiccities", wrapAsync(listingController.iconiccities));
router.get("/result",wrapAsync(listingController.results));
router.route("/:id").get(wrapAsync(listingController.showListing)).put(isLoggedIn,isOwner,upload.single("listing[image]"),validatelisting,wrapAsync(listingController.updateListing)).delete(isLoggedIn,isOwner,wrapAsync( listingController.destroyListing));
router.get("/:id/edit",isLoggedIn,isOwner,wrapAsync(listingController.renderEditForm));

module.exports = router;